'use client';

import React, { useState, useRef, useEffect } from 'react';
import {
    Box,
    Typography,
    Card,
    TextField,
    Button,
    Grid,
    IconButton,
    Paper,
    Divider,
    CircularProgress,
    Chip,
    Avatar
} from '@mui/material';
import SendIcon from '@mui/icons-material/Send';
import CodeIcon from '@mui/icons-material/Code';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import PlayArrowIcon from '@mui/icons-material/PlayArrow';
import SmartToyIcon from '@mui/icons-material/SmartToy';
import PersonIcon from '@mui/icons-material/Person';

interface Message {
    id: number;
    role: 'user' | 'assistant';
    content: string;
    isCode?: boolean;
}

const INITIAL_CODE = `# אסטרטגיה ריקה
# תאר את הרעיון שלך בצ'אט כדי לייצר קוד...
`;

export default function AlgoBuilderPage() {
    const [messages, setMessages] = useState<Message[]>([
        { id: 1, role: 'assistant', content: 'שלום! אני הארכיטקט האלגוריתמי שלך. ספר לי על רעיון המסחר שלך (למשל: "תקנה ביטקוין כשה-RSI נמוך מ-30") ואני אכתוב את הקוד עבורך.' }
    ]);
    const [input, setInput] = useState('');
    const [generatedCode, setGeneratedCode] = useState(INITIAL_CODE);
    const [isTyping, setIsTyping] = useState(false);
    const messagesEndRef = useRef<null | HTMLDivElement>(null);

    const scrollToBottom = () => {
        messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    };

    useEffect(() => {
        scrollToBottom();
    }, [messages]);

    const handleSend = () => {
        if (!input.trim()) return;

        const userMsg: Message = { id: Date.now(), role: 'user', content: input };
        setMessages(prev => [...prev, userMsg]);
        setInput('');
        setIsTyping(true);

        // Simulate Gemini generating code
        setTimeout(() => {
            const isRsiStrategy = userMsg.content.toLowerCase().includes('rsi');
            const isMacdStrategy = userMsg.content.toLowerCase().includes('macd');

            let newCode = generatedCode;
            let responseText = "הנה הקוד לאסטרטגיה שלך.";

            if (isRsiStrategy) {
                newCode = `
# RSI Strategy generated by Gemini
import talib
import numpy as np

def strategy(data):
    rsi = talib.RSI(data['close'], timeperiod=14)
    
    if rsi[-1] < 30:
        return 'BUY'
    elif rsi[-1] > 70:
        return 'SELL'
    else:
        return 'HOLD'
`;
                responseText = "הבנתי, אסטרטגיית RSI קלאסית. הגדרתי את תנאי הקנייה מתחת ל-30 ואת המכירה מעל 70. הנה קוד ה-Python המעודכן:";
            } else if (isMacdStrategy) {
                newCode = `
# MACD Strategy generated by Gemini
import talib

def strategy(data):
    macd, signal, hist = talib.MACD(data['close'])
    
    # Crossover logic
    if macd[-1] > signal[-1] and macd[-2] <= signal[-2]:
        return 'BUY'
    elif macd[-1] < signal[-1] and macd[-2] >= signal[-2]:
        return 'SELL'
    return 'HOLD'
`;
                responseText = "בניתי לך אסטרטגיית חציית MACD. המערכת תזהה את נקודות החיתוך בין קו ה-MACD לקו הסיגנל.";
            } else {
                newCode = `
# Custom Strategy Placeholder
def strategy(data):
    # Logic based on: "${userMsg.content}"
    # waiting for specific indicators...
    return 'HOLD'
`;
                responseText = "רעיון מעניין. יצרתי שלד לאסטרטגיה הזו, אבל אצטרך פרטים נוספים על האינדיקטורים המדויקים.";
            }

            setGeneratedCode(newCode);
            setMessages(prev => [...prev, { id: Date.now() + 1, role: 'assistant', content: responseText }]);
            setIsTyping(false);
        }, 1500);
    };

    return (
        <Box className="animate-fade-in" sx={{ height: 'calc(100vh - 100px)', display: 'flex', gap: 2, p: 1 }}>

            {/* Left: Chat Interface */}
            <Paper sx={{
                flex: 1,
                display: 'flex',
                flexDirection: 'column',
                bgcolor: 'rgba(15, 23, 42, 0.6)',
                backdropFilter: 'blur(20px)',
                border: '1px solid rgba(255,255,255,0.05)',
                borderRadius: 4,
                overflow: 'hidden'
            }}>
                <Box sx={{ p: 2, borderBottom: '1px solid rgba(255,255,255,0.05)', display: 'flex', alignItems: 'center', gap: 1 }}>
                    <SmartToyIcon color="primary" />
                    <Typography variant="h6" fontWeight="bold">הארכיטקט (Gemini)</Typography>
                </Box>

                <Box sx={{ flex: 1, overflow: 'auto', p: 2, display: 'flex', flexDirection: 'column', gap: 2 }}>
                    {messages.map((msg) => (
                        <Box key={msg.id} sx={{
                            alignSelf: msg.role === 'user' ? 'flex-end' : 'flex-start',
                            maxWidth: '85%',
                            display: 'flex',
                            gap: 1.5,
                            flexDirection: msg.role === 'user' ? 'row-reverse' : 'row'
                        }}>
                            <Avatar sx={{
                                width: 32, height: 32,
                                bgcolor: msg.role === 'user' ? 'secondary.main' : 'primary.main',
                                fontSize: '1rem'
                            }}>
                                {msg.role === 'user' ? <PersonIcon fontSize="inherit" /> : <SmartToyIcon fontSize="inherit" />}
                            </Avatar>
                            <Paper sx={{
                                p: 2,
                                borderRadius: 3,
                                bgcolor: msg.role === 'user' ? 'primary.main' : 'rgba(255,255,255,0.05)',
                                color: msg.role === 'user' ? 'black' : 'white',
                                boxShadow: '0 2px 10px rgba(0,0,0,0.1)'
                            }}>
                                <Typography variant="body2">{msg.content}</Typography>
                            </Paper>
                        </Box>
                    ))}
                    {isTyping && (
                        <Box sx={{ display: 'flex', gap: 1, ml: 1, alignItems: 'center' }}>
                            <CircularProgress size={16} />
                            <Typography variant="caption" color="text.secondary">Gemini כותב קוד...</Typography>
                        </Box>
                    )}
                    <div ref={messagesEndRef} />
                </Box>

                <Box sx={{ p: 2, bgcolor: 'rgba(0,0,0,0.2)', display: 'flex', gap: 1 }}>
                    <TextField
                        fullWidth
                        placeholder="תאר את האסטרטגיה שלך..."
                        size="small"
                        value={input}
                        onChange={(e) => setInput(e.target.value)}
                        onKeyPress={(e) => e.key === 'Enter' && handleSend()}
                        sx={{ bgcolor: 'rgba(255,255,255,0.05)', borderRadius: 1 }}
                    />
                    <IconButton color="primary" onClick={handleSend} disabled={!input.trim() || isTyping}>
                        <SendIcon />
                    </IconButton>
                </Box>
            </Paper>

            {/* Right: Code Editor & Preview */}
            <Paper sx={{
                flex: 1,
                display: 'flex',
                flexDirection: 'column',
                bgcolor: '#0f172a',
                border: '1px solid rgba(255,255,255,0.05)',
                borderRadius: 4,
                overflow: 'hidden'
            }}>
                <Box sx={{ p: 2, borderBottom: '1px solid rgba(255,255,255,0.05)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                        <CodeIcon color="secondary" />
                        <Typography variant="h6" fontWeight="bold">עורך קוד חי</Typography>
                        <Chip label="Python" size="small" sx={{ height: 20, bgcolor: 'rgba(34, 211, 238, 0.1)', color: '#22D3EE' }} />
                    </Box>
                    <Box>
                        <IconButton size="small" sx={{ color: 'text.secondary' }}>
                            <ContentCopyIcon fontSize="small" />
                        </IconButton>
                    </Box>
                </Box>

                <Box sx={{ flex: 1, p: 0, overflow: 'auto', bgcolor: '#0b1120' }}>
                    <pre style={{
                        margin: 0,
                        padding: '20px',
                        fontFamily: "'Fira Code', monospace",
                        fontSize: '14px',
                        lineHeight: '1.6',
                        color: '#e2e8f0'
                    }}>
                        {generatedCode}
                    </pre>
                </Box>

                <Box sx={{ p: 2, borderTop: '1px solid rgba(255,255,255,0.05)', display: 'flex', justifyContent: 'flex-end' }}>
                    <Button
                        variant="contained"
                        color="success"
                        startIcon={<PlayArrowIcon />}
                        href="/backtester" // In a real app we would pass state via context/params
                        sx={{ fontWeight: 'bold', px: 3 }}
                    >
                        בדוק במכונת הזמן
                    </Button>
                </Box>
            </Paper>

        </Box>
    );
}
